server:
  port: 8080
  undertow:
    threads:
      io: 4
      worker: 256
    buffer-size: 1024
    direct-buffers: true
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  servlet:
    context-path: /integration
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  datasource:
    #    master:
    url: jdbc:mysql://127.0.0.1:3306/integration?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Ycl499475142!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 100
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      repositories:
        enabled: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      resolve-lazily: false
  web:
    resources:
      # 设置静态资源路径，以jar宝发布时，在jar包的目录下
      static-locations: classpath:/static/,file:static/
  mvc:
    static-path-pattern: /static/**
#      host: 127.0.0.1
#      port: 6379
#      connect-timeout: 180000
#      database: 0
#      lettuce:
#        pool:
#          # 最大阻塞等待时间，负数表示没有限制
#          max-wait: -1
#          # 连接池中的最大空闲连接
#          max-idle: 5
#          # 连接池中的最小空闲连接
#          min-idle: 0
#          # 连接池中最大连接数，负数表示没有限制
#          max-active: 20
camel:
  springboot:
    backlog-tracing: false
mybatis-plus:
  mapper-locations: classpath:cn/net/integration/**/mapper/xml/*Mapper.xml
springdoc:
  swagger-ui:
    path: /swagger
sa-token:
  token-prefix: integration
# 文件上传绝对路径
my.upload.path: /root/integration/upload/
# 文件上传根目录
direPath: upload
# 文件上传的根目录的上级绝对路径
rootPath: /root/integration